name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy Contember to production
      run: npm run deploy ${{ secrets.CONTEMBER_DSN }} -- --yes